services:
  puppeteer-app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - .:/home/pptruser/app
      - ./data:/home/pptruser/app/data
    ports:
      - "3000-3001:3000"
    environment:
      - PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
    command: ["node", "--experimental-modules", "server.js"]
    cap_add:
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
